//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormWebServices.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tbalumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet tbalumno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tbalumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> tbalumnoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertAlumno(string ci, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task InsertAlumnoAsync(string ci, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateAlumno(string ci, string nuevoNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateAlumnoAsync(string ci, string nuevoNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteAlumno(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAlumnoAsync(string ci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : FormWebServices.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<FormWebServices.ServiceReference1.WebService1Soap>, FormWebServices.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet tbalumno() {
            return base.Channel.tbalumno();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> tbalumnoAsync() {
            return base.Channel.tbalumnoAsync();
        }
        
        public void InsertAlumno(string ci, string nombre) {
            base.Channel.InsertAlumno(ci, nombre);
        }
        
        public System.Threading.Tasks.Task InsertAlumnoAsync(string ci, string nombre) {
            return base.Channel.InsertAlumnoAsync(ci, nombre);
        }
        
        public void UpdateAlumno(string ci, string nuevoNombre) {
            base.Channel.UpdateAlumno(ci, nuevoNombre);
        }
        
        public System.Threading.Tasks.Task UpdateAlumnoAsync(string ci, string nuevoNombre) {
            return base.Channel.UpdateAlumnoAsync(ci, nuevoNombre);
        }
        
        public void DeleteAlumno(string ci) {
            base.Channel.DeleteAlumno(ci);
        }
        
        public System.Threading.Tasks.Task DeleteAlumnoAsync(string ci) {
            return base.Channel.DeleteAlumnoAsync(ci);
        }
    }
}
